# Generated by Django 5.2.14 on 2026-05-07 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Animal Categories',
            },
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('scientific_name', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='animal_images/')),
                ('habitat', models.CharField(blank=True, max_length=255)),
                ('diet', models.CharField(blank=True, max_length=150)),
                ('lifespan', models.CharField(blank=True, max_length=100)),
                ('size', models.CharField(blank=True, max_length=100)),
                ('conservation_status', models.CharField(choices=[('Least Concern', 'Least Concern'), ('Near Threatened', 'Near Threatened'), ('Vulnerable', 'Vulnerable'), ('Endangered', 'Endangered'), ('Critically Endangered', 'Critically Endangered'), ('Extinct in the Wild', 'Extinct in the Wild'), ('Extinct', 'Extinct'), ('Unknown', 'Unknown')], default='Unknown', max_length=50)),
                ('description', models.TextField()),
                ('fun_fact', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='animals.animalcategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
