# Generated by Django 5.2.14 on 2026-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='diet',
            field=models.CharField(blank=True, choices=[('Carnivore', 'Carnivore'), ('Herbivore', 'Herbivore'), ('Omnivore', 'Omnivore'), ('Insectivore', 'Insectivore')], max_length=150),
        ),
        migrations.AlterField(
            model_name='animal',
            name='habitat',
            field=models.CharField(blank=True, choices=[('Forest', 'Forest'), ('Ocean', 'Ocean'), ('Desert', 'Desert'), ('Grassland', 'Grassland'), ('Wetland', 'Wetland'), ('Mountain', 'Mountain'), ('Arctic', 'Arctic')], max_length=150),
        ),
    ]
