# Generated by Django 5.2.14 on 2026-05-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_alter_animal_diet_alter_animal_habitat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='created_at',
        ),
        migrations.AddField(
            model_name='animal',
            name='wiki_image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='wiki_page_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='wiki_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='wiki_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
