# Generated by Django 5.2.14 on 2026-05-08 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_remove_animal_created_at_animal_wiki_image_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=150)),
                ('country', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='animals.animal')),
            ],
        ),
    ]
