# Generated by Django 5.2.14 on 2026-05-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_animallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='countries',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='animal',
            name='map_points',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
