# Generated by Django 5.2.14 on 2026-05-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_animal_countries_animal_map_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='natural_enemies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
