# Generated by Django 5.2.14 on 2026-05-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_puzzlescore'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('youtube', 'YouTube Shorts'), ('tiktok', 'TikTok')], max_length=20)),
                ('video_url', models.URLField()),
                ('embed_url', models.URLField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='animals.animal')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='animals.animalcategory')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
