from django.db import migrations, models


STARTER_ZOOS = [
    {
        "name": "Bronx Zoo",
        "address": "2300 Southern Blvd",
        "city": "Bronx",
        "state": "NY",
        "zipcode": "10460",
        "latitude": 40.8506,
        "longitude": -73.8769,
        "website": "https://bronxzoo.com",
        "zoo_type": "zoo",
    },
    {
        "name": "Central Park Zoo",
        "address": "East 64th Street",
        "city": "New York",
        "state": "NY",
        "zipcode": "10021",
        "latitude": 40.7678,
        "longitude": -73.9718,
        "website": "https://centralparkzoo.com",
        "zoo_type": "zoo",
    },
    {
        "name": "San Diego Zoo",
        "address": "2920 Zoo Dr",
        "city": "San Diego",
        "state": "CA",
        "zipcode": "92101",
        "latitude": 32.7353,
        "longitude": -117.1490,
        "website": "https://sandiegozoowildlifealliance.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Los Angeles Zoo",
        "address": "5333 Zoo Dr",
        "city": "Los Angeles",
        "state": "CA",
        "zipcode": "90027",
        "latitude": 34.1480,
        "longitude": -118.2861,
        "website": "https://lazoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Smithsonian National Zoo",
        "address": "3001 Connecticut Ave NW",
        "city": "Washington",
        "state": "DC",
        "zipcode": "20008",
        "latitude": 38.9296,
        "longitude": -77.0498,
        "website": "https://nationalzoo.si.edu",
        "zoo_type": "zoo",
    },
    {
        "name": "Lincoln Park Zoo",
        "address": "2001 N Clark St",
        "city": "Chicago",
        "state": "IL",
        "zipcode": "60614",
        "latitude": 41.9211,
        "longitude": -87.6338,
        "website": "https://lpzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Brookfield Zoo Chicago",
        "address": "8400 31st St",
        "city": "Brookfield",
        "state": "IL",
        "zipcode": "60513",
        "latitude": 41.8313,
        "longitude": -87.8368,
        "website": "https://brookfieldzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Houston Zoo",
        "address": "6200 Hermann Park Dr",
        "city": "Houston",
        "state": "TX",
        "zipcode": "77030",
        "latitude": 29.7112,
        "longitude": -95.3909,
        "website": "https://houstonzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Dallas Zoo",
        "address": "650 S R L Thornton Fwy",
        "city": "Dallas",
        "state": "TX",
        "zipcode": "75203",
        "latitude": 32.7411,
        "longitude": -96.8150,
        "website": "https://dallaszoo.com",
        "zoo_type": "zoo",
    },
    {
        "name": "Columbus Zoo and Aquarium",
        "address": "4850 W Powell Rd",
        "city": "Powell",
        "state": "OH",
        "zipcode": "43065",
        "latitude": 40.1578,
        "longitude": -83.1187,
        "website": "https://columbuszoo.org",
        "zoo_type": "aquarium",
    },
    {
        "name": "Zoo Atlanta",
        "address": "800 Cherokee Ave SE",
        "city": "Atlanta",
        "state": "GA",
        "zipcode": "30315",
        "latitude": 33.7335,
        "longitude": -84.3733,
        "website": "https://zooatlanta.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Saint Louis Zoo",
        "address": "1 Government Dr",
        "city": "St. Louis",
        "state": "MO",
        "zipcode": "63110",
        "latitude": 38.6358,
        "longitude": -90.2907,
        "website": "https://stlzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Denver Zoo Conservation Alliance",
        "address": "2300 Steele St",
        "city": "Denver",
        "state": "CO",
        "zipcode": "80205",
        "latitude": 39.7503,
        "longitude": -104.9507,
        "website": "https://denverzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Phoenix Zoo",
        "address": "455 N Galvin Pkwy",
        "city": "Phoenix",
        "state": "AZ",
        "zipcode": "85008",
        "latitude": 33.4511,
        "longitude": -111.9480,
        "website": "https://phoenixzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Oregon Zoo",
        "address": "4001 SW Canyon Rd",
        "city": "Portland",
        "state": "OR",
        "zipcode": "97221",
        "latitude": 45.5099,
        "longitude": -122.7157,
        "website": "https://oregonzoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Woodland Park Zoo",
        "address": "5500 Phinney Ave N",
        "city": "Seattle",
        "state": "WA",
        "zipcode": "98103",
        "latitude": 47.6685,
        "longitude": -122.3501,
        "website": "https://zoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Zoo Miami",
        "address": "12400 SW 152nd St",
        "city": "Miami",
        "state": "FL",
        "zipcode": "33177",
        "latitude": 25.6115,
        "longitude": -80.3983,
        "website": "https://zoomiami.org",
        "zoo_type": "zoo",
    },
    {
        "name": "Audubon Zoo",
        "address": "6500 Magazine St",
        "city": "New Orleans",
        "state": "LA",
        "zipcode": "70118",
        "latitude": 29.9211,
        "longitude": -90.1227,
        "website": "https://audubonnatureinstitute.org/zoo",
        "zoo_type": "zoo",
    },
    {
        "name": "Nashville Zoo",
        "address": "3777 Nolensville Pike",
        "city": "Nashville",
        "state": "TN",
        "zipcode": "37211",
        "latitude": 36.0906,
        "longitude": -86.7538,
        "website": "https://nashvillezoo.org",
        "zoo_type": "zoo",
    },
    {
        "name": "The Florida Aquarium",
        "address": "701 Channelside Dr",
        "city": "Tampa",
        "state": "FL",
        "zipcode": "33602",
        "latitude": 27.9427,
        "longitude": -82.4458,
        "website": "https://flaquarium.org",
        "zoo_type": "aquarium",
    },
]


def seed_zoos(apps, schema_editor):
    Zoo = apps.get_model("animals", "Zoo")

    for zoo_data in STARTER_ZOOS:
        Zoo.objects.update_or_create(
            name=zoo_data["name"],
            defaults=zoo_data,
        )


def remove_seed_zoos(apps, schema_editor):
    Zoo = apps.get_model("animals", "Zoo")
    zoo_names = [zoo["name"] for zoo in STARTER_ZOOS]
    Zoo.objects.filter(name__in=zoo_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0011_newslettersubscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Zoo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=120)),
                ("state", models.CharField(max_length=120)),
                ("zipcode", models.CharField(blank=True, max_length=20)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("website", models.URLField(blank=True, max_length=500)),
                ("zoo_type", models.CharField(choices=[("zoo", "Zoo"), ("aquarium", "Aquarium"), ("safari_park", "Safari Park"), ("sanctuary", "Sanctuary")], default="zoo", max_length=30)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.RunPython(seed_zoos, remove_seed_zoos),
    ]
