from django.db import migrations, models


STATE_DIRECTORY_ZOOS = [
    {
        "name": "Birmingham Zoo",
        "address": "",
        "city": "Birmingham",
        "state": "AL",
        "zipcode": "35223",
        "latitude": 33.4864,
        "longitude": -86.7850,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Alaska SeaLife Center",
        "address": "",
        "city": "Seward",
        "state": "AK",
        "zipcode": "99664",
        "latitude": 60.1049,
        "longitude": -149.4422,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Little Rock Zoo",
        "address": "",
        "city": "Little Rock",
        "state": "AR",
        "zipcode": "72205",
        "latitude": 34.7494,
        "longitude": -92.3340,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Mystic Aquarium",
        "address": "",
        "city": "Mystic",
        "state": "CT",
        "zipcode": "06355",
        "latitude": 41.3549,
        "longitude": -71.9665,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Brandywine Zoo",
        "address": "",
        "city": "Wilmington",
        "state": "DE",
        "zipcode": "19802",
        "latitude": 39.7664,
        "longitude": -75.5466,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Honolulu Zoo",
        "address": "",
        "city": "Honolulu",
        "state": "HI",
        "zipcode": "96815",
        "latitude": 21.2713,
        "longitude": -157.8217,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Zoo Boise",
        "address": "",
        "city": "Boise",
        "state": "ID",
        "zipcode": "83702",
        "latitude": 43.6057,
        "longitude": -116.2035,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Indianapolis Zoo",
        "address": "",
        "city": "Indianapolis",
        "state": "IN",
        "zipcode": "46222",
        "latitude": 39.7496,
        "longitude": -86.1797,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Blank Park Zoo",
        "address": "",
        "city": "Des Moines",
        "state": "IA",
        "zipcode": "50315",
        "latitude": 41.5417,
        "longitude": -93.6250,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Sedgwick County Zoo",
        "address": "",
        "city": "Wichita",
        "state": "KS",
        "zipcode": "67212",
        "latitude": 37.7307,
        "longitude": -97.3843,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Louisville Zoo",
        "address": "",
        "city": "Louisville",
        "state": "KY",
        "zipcode": "40213",
        "latitude": 38.2053,
        "longitude": -85.7071,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Maine State Aquarium",
        "address": "194 McKown Point Road",
        "city": "West Boothbay Harbor",
        "state": "ME",
        "zipcode": "04575",
        "latitude": 43.8526,
        "longitude": -69.6288,
        "website": "https://www.maine.gov/dmr/programs/education-division/aquarium",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "National Aquarium",
        "address": "",
        "city": "Baltimore",
        "state": "MD",
        "zipcode": "21202",
        "latitude": 39.2853,
        "longitude": -76.6071,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Franklin Park Zoo",
        "address": "",
        "city": "Boston",
        "state": "MA",
        "zipcode": "02121",
        "latitude": 42.3028,
        "longitude": -71.0901,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Detroit Zoo",
        "address": "",
        "city": "Royal Oak",
        "state": "MI",
        "zipcode": "48067",
        "latitude": 42.4690,
        "longitude": -83.1498,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Minnesota Zoo",
        "address": "",
        "city": "Apple Valley",
        "state": "MN",
        "zipcode": "55124",
        "latitude": 44.7811,
        "longitude": -93.2109,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Hattiesburg Zoo",
        "address": "",
        "city": "Hattiesburg",
        "state": "MS",
        "zipcode": "39401",
        "latitude": 31.3271,
        "longitude": -89.3013,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Shark Reef Aquarium",
        "address": "",
        "city": "Las Vegas",
        "state": "NV",
        "zipcode": "89119",
        "latitude": 36.0919,
        "longitude": -115.1764,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Living Shores Aquarium",
        "address": "850 NH Route 16",
        "city": "Glen",
        "state": "NH",
        "zipcode": "03838",
        "latitude": 44.0998,
        "longitude": -71.1817,
        "website": "https://www.livingshores.com/",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Adventure Aquarium",
        "address": "",
        "city": "Camden",
        "state": "NJ",
        "zipcode": "08103",
        "latitude": 39.9450,
        "longitude": -75.1297,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "ABQ BioPark",
        "address": "",
        "city": "Albuquerque",
        "state": "NM",
        "zipcode": "87104",
        "latitude": 35.0917,
        "longitude": -106.6766,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "North Carolina Zoo",
        "address": "",
        "city": "Asheboro",
        "state": "NC",
        "zipcode": "27205",
        "latitude": 35.6308,
        "longitude": -79.7645,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Dakota Zoo",
        "address": "",
        "city": "Bismarck",
        "state": "ND",
        "zipcode": "58504",
        "latitude": 46.7909,
        "longitude": -100.7824,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Oklahoma City Zoo",
        "address": "",
        "city": "Oklahoma City",
        "state": "OK",
        "zipcode": "73111",
        "latitude": 35.5226,
        "longitude": -97.4743,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Philadelphia Zoo",
        "address": "",
        "city": "Philadelphia",
        "state": "PA",
        "zipcode": "19104",
        "latitude": 39.9740,
        "longitude": -75.1950,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Roger Williams Park Zoo",
        "address": "",
        "city": "Providence",
        "state": "RI",
        "zipcode": "02907",
        "latitude": 41.7854,
        "longitude": -71.4121,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Riverbanks Zoo and Garden",
        "address": "",
        "city": "Columbia",
        "state": "SC",
        "zipcode": "29210",
        "latitude": 34.0098,
        "longitude": -81.0731,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Great Plains Zoo",
        "address": "",
        "city": "Sioux Falls",
        "state": "SD",
        "zipcode": "57104",
        "latitude": 43.5476,
        "longitude": -96.7713,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Utah's Hogle Zoo",
        "address": "",
        "city": "Salt Lake City",
        "state": "UT",
        "zipcode": "84108",
        "latitude": 40.7678,
        "longitude": -111.8252,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Virginia Aquarium and Marine Science Center",
        "address": "",
        "city": "Virginia Beach",
        "state": "VA",
        "zipcode": "23451",
        "latitude": 36.8206,
        "longitude": -75.9779,
        "website": "",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "ECHO, Leahy Center for Lake Champlain",
        "address": "1 College St.",
        "city": "Burlington",
        "state": "VT",
        "zipcode": "05401",
        "latitude": 44.4778,
        "longitude": -73.2193,
        "website": "https://www.echovermont.org/",
        "image_url": "",
        "zoo_type": "aquarium",
        "is_active": True,
    },
    {
        "name": "Oglebay Good Zoo",
        "address": "465 Lodge Drive",
        "city": "Wheeling",
        "state": "WV",
        "zipcode": "26003",
        "latitude": 40.1028,
        "longitude": -80.6451,
        "website": "https://oglebay.com/good-zoo",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
    {
        "name": "Milwaukee County Zoo",
        "address": "",
        "city": "Milwaukee",
        "state": "WI",
        "zipcode": "53226",
        "latitude": 43.0337,
        "longitude": -88.0370,
        "website": "",
        "image_url": "",
        "zoo_type": "zoo",
        "is_active": True,
    },
]


def add_state_directory_zoos(apps, schema_editor):
    Zoo = apps.get_model("animals", "Zoo")

    for zoo_data in STATE_DIRECTORY_ZOOS:
        Zoo.objects.update_or_create(
            name=zoo_data["name"],
            defaults=zoo_data,
        )


def remove_state_directory_zoos(apps, schema_editor):
    Zoo = apps.get_model("animals", "Zoo")
    zoo_names = [zoo["name"] for zoo in STATE_DIRECTORY_ZOOS]
    Zoo.objects.filter(name__in=zoo_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("animals", "0013_zoo_image_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zoo",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(add_state_directory_zoos, remove_state_directory_zoos),
    ]
